### ISSUE TITLE
Why don't add participants at the end of the file ?

### ISSUE THREAD

**Issue by amritsrivastava** [CodeDocsJECRC/hacktoberfest2018#44]
@akashlakhera what is the reason behind the note added at the end of the file?

**Comment by akashlakhera** [comment]
If two people fork at the same time, adding at the end creates a merge conflict, git thinks that both people are trying to edit the same line.
While if they add in between two lines git recognises the changes are meant to be different and no conflicts occur.

**Comment by amritsrivastava** [comment]
Okay :+1:

**Comment by akashlakhera** [comment]
I got the idea from this repo.
[firstcontributions](https://github.com/firstcontributions/first-contributions#make-necessary-changes-and-commit-those-changes)
