### ISSUE TITLE
Why are usernames under 'Stats'?

### ISSUE THREAD

**Issue by accakks** [CodeDocsJECRC/hacktoberfest2018#69]
In the table, some people have added Github profile links to their name, whereas some people have added username under stats. Stats are for number of PRs right?

**Comment by maddhruv** [comment]
Please add more info!
I dont understand

**Comment by accakks** [comment]
Added

**Comment by maddhruv** [comment]
GitHub profile links are complimentary
while
username with a link to _stats_ is necessary element

**Comment by maddhruv** [comment]
> Stats are for number of PRs right?

yes

**Comment by accakks** [comment]
Okay got it. Closing this.
